### ISSUE TITLE
Question abut texture streaming

### ISSUE THREAD

**Issue by EverydayMayhem** [RedDot-3ND7355/BnS-Buddy#10]
Sorry to ask about this, but does enabling 'No texture streaming feature' supposed to improve your fps? I was checking some stuff and noticed that enabling or disabling this feature gives near to none effect on fps, and I'm kinda curios, because it seems that this feature should make some difference, or it's not guaranteed to improve fps? How can I even recognize if this feature is working in-game?
Sorry for lots of dumb questions

**Comment by RedDot-3ND7355** [comment]
"Texture Streaming": Textures are loaded as needed, rather than all cached at the start. If your hardware is a bit outdated (or your HDD is horribly fragmented) you can notice some 'hitching' as those textures are loaded. Some engines, like the Source engine, allow you to force all textures to be pre-cached, but this dramatically increases load times and can cause more problems.

So disabling that feature often helps to decrease loading time and minimalise the issues.
lastly, it prevents reloading textures without changing area. (using winstride).
